/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package si.fri.algotest.analysis.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import si.fri.algotest.entities.EProject;
import si.fri.algotest.entities.EQuery;
import si.fri.algotest.entities.NameAndAbrev;
import si.fri.algotest.entities.Project;

/**
 *
 * @author tomaz
 */
public class QueryComposer extends javax.swing.JPanel {

  Project project;
  
  NAAPanel [] algNAAs, tstsNAAs, infieldNAAs, outfieldNAAs;
  
  ActionListener outerChangeListener, innerChangeListner;
  

  /**
   * Creates new form QueryComposer
   */
  public QueryComposer() {
    initComponents();
    
    innerChangeListner= new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
	dataChanged();
	if (outerChangeListener != null)
	outerChangeListener.actionPerformed(e);
      }
    };
  }

  public void setProject(Project project) {
    this.project = project;
    
    setAlgsAndFields();
  }
  
  public void setOuterChangeListener(ActionListener action) {
    ActionListener a;
    this.outerChangeListener = action;
  }
  
  // poslusam spremembe na panelih in ukrepam (primer: če se dodajo nova polja
  // med filde, moram spremeniti sortby panel)
  void dataChanged() {
  }
  
  private NAAPanel [] createNAAPanels(String [] names, JPanel panel) {
    NAAPanel [] result = new NAAPanel[names.length];
    if (names == null) return result;
    
    for(int i=0; i<names.length;i++) {
      result[i] = new NAAPanel(names[i], names[i], innerChangeListner);
      panel.add(result[i]);
    }
    return result;
  }

  private String [] getNAAsAsStringArray(NAAPanel [] naaPanel) {
    int count = 0;
    for (int i = 0; i < naaPanel.length; i++) {
      if (naaPanel[i].isSelected()) count++;
    }
    String [] result = new String[count];
    int k=0;
    for (int i = 0; i < naaPanel.length; i++) {
      if (!naaPanel[i].isSelected()) continue;
     
      result[k++] = naaPanel[i].getNAA().toString();
    }
    
    return result;
  }
  
  private void setNAAPanelValues(NameAndAbrev[] naas, NAAPanel [] naaPanel) {
    for (int i = 0; i < naaPanel.length; i++) {
      naaPanel[i].setSelected(false);
    }
    for (NameAndAbrev naa : naas) {
      for (NAAPanel naaPanel1 : naaPanel) {
        if (naaPanel1.correspondsTo(naa)) {
          naaPanel1.setValues(naa, true);
          break;
        }
      }
    }
  }
  
  private void setAlgsAndFields() {
    if (project == null) return;
    
    EProject eProject = project.getProject();
    if (eProject == null) return;
    
    String [] algs = eProject.getStringArray(EProject.ID_Algorithms);    
    String [] tsts = eProject.getStringArray(EProject.ID_TestSets);
      
    
    algNAAs = createNAAPanels(algs, algPanel);
    tstsNAAs = createNAAPanels(tsts, tstsPanel);

    infieldNAAs  = createNAAPanels(project.getTestParameters(),   infieldPanel); 
    outfieldNAAs = createNAAPanels(project.getResultParameters(), outfieldPanel);

  }
  
  public EQuery getQuery() {
    String [] algs = getNAAsAsStringArray(algNAAs);
    String [] tsts = getNAAsAsStringArray(tstsNAAs);
    String [] inf  = getNAAsAsStringArray(infieldNAAs);
    String [] outf = getNAAsAsStringArray(outfieldNAAs);
    
    // currently only one GropuBy, one filter and one sortby is suported
    
    return new EQuery(algs, tsts, inf, outf, new String[] {groupbyTF.getText()}, 
                      new String[] {filterTF.getText()}, new String[] {sortbyTF.getText()});
  }
  
  public void setQuery(EQuery query) {
    try {
      setNAAPanelValues(query.getNATabFromJSONArray(EQuery.ID_Algorithms), algNAAs);
      setNAAPanelValues(query.getNATabFromJSONArray(EQuery.ID_TestSets), tstsNAAs);
      setNAAPanelValues(query.getNATabFromJSONArray(EQuery.ID_inParameters), infieldNAAs);
      setNAAPanelValues(query.getNATabFromJSONArray(EQuery.ID_outParameters), outfieldNAAs);
    
    // currently only one GropuBy, one Filter and one SortBy is supported
      String[] gb = query.getStringArray(EQuery.ID_GroupBy);
      groupbyTF.setText(gb.length > 0 ? gb[0] : "");
  
      String[] ft = query.getStringArray(EQuery.ID_Filter);
      filterTF.setText(ft.length > 0 ? ft[0] : "");
      
      String[] sb = query.getStringArray(EQuery.ID_SortBy);
      sortbyTF.setText(sb.length > 0 ?sb[0] : "");
      
    } catch (Exception e) {}
  }
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel4 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    algPanel = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    infieldPanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    outfieldPanel = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    tstsPanel = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    groupByPanel = new javax.swing.JPanel();
    groupbyTF = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    groupByPanel1 = new javax.swing.JPanel();
    filterTF = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    groupByPanel2 = new javax.swing.JPanel();
    sortbyTF = new javax.swing.JTextField();

    org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 100, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 100, Short.MAX_VALUE)
    );

    setLayout(new java.awt.GridBagLayout());

    jPanel2.setLayout(new java.awt.GridBagLayout());

    jLabel2.setText("Algorithms");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    jPanel2.add(jLabel2, gridBagConstraints);

    algPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    algPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    jPanel2.add(algPanel, gridBagConstraints);

    jLabel3.setText("Input Fields");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    jPanel2.add(jLabel3, gridBagConstraints);

    infieldPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    infieldPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    jPanel2.add(infieldPanel, gridBagConstraints);

    jLabel1.setText("Output Fields");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    jPanel2.add(jLabel1, gridBagConstraints);

    outfieldPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    outfieldPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    jPanel2.add(outfieldPanel, gridBagConstraints);

    jLabel4.setText("Testsets");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    jPanel2.add(jLabel4, gridBagConstraints);

    tstsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    tstsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    jPanel2.add(tstsPanel, gridBagConstraints);

    jLabel6.setText("GroupBy");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    jPanel2.add(jLabel6, gridBagConstraints);

    groupByPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    groupByPanel.setLayout(new java.awt.BorderLayout());
    groupByPanel.add(groupbyTF, java.awt.BorderLayout.CENTER);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    jPanel2.add(groupByPanel, gridBagConstraints);

    jLabel7.setText("Filter");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    jPanel2.add(jLabel7, gridBagConstraints);

    groupByPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    groupByPanel1.setLayout(new java.awt.BorderLayout());
    groupByPanel1.add(filterTF, java.awt.BorderLayout.CENTER);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    jPanel2.add(groupByPanel1, gridBagConstraints);

    jLabel8.setText("SortBy");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
    jPanel2.add(jLabel8, gridBagConstraints);

    groupByPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    groupByPanel2.setLayout(new java.awt.BorderLayout());
    groupByPanel2.add(sortbyTF, java.awt.BorderLayout.CENTER);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    jPanel2.add(groupByPanel2, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(jPanel2, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel algPanel;
  private javax.swing.JTextField filterTF;
  private javax.swing.JPanel groupByPanel;
  private javax.swing.JPanel groupByPanel1;
  private javax.swing.JPanel groupByPanel2;
  private javax.swing.JTextField groupbyTF;
  private javax.swing.JPanel infieldPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel outfieldPanel;
  private javax.swing.JTextField sortbyTF;
  private javax.swing.JPanel tstsPanel;
  // End of variables declaration//GEN-END:variables
}
